# Generated by Django 4.1.7 on 2023-03-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fields", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("laltitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("description", models.TextField()),
                ("state", models.BooleanField(default=False)),
                ("price", models.FloatField()),
                ("urlPhoto", models.URLField()),
                ("soilType", models.CharField(max_length=20)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fields.type"
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fields.zone"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Terrain",
        ),
    ]
