# Generated by Django 4.1.7 on 2023-03-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fields", "0002_field_delete_terrain"),
    ]

    operations = [
        migrations.RenameField(
            model_name="field",
            old_name="soilType",
            new_name="soil_type",
        ),
        migrations.RenameField(
            model_name="field",
            old_name="urlPhoto",
            new_name="url_photo",
        ),
    ]
