# Generated by Django 4.1.7 on 2023-04-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fields", "0003_rename_soiltype_field_soil_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="field",
            old_name="laltitude",
            new_name="latitude",
        ),
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="field",
            name="soil_type",
            field=models.CharField(
                choices=[("synthetique", "naturelle"), ("Synthetique", "Naturelle")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="fields.zone",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(
                choices=[("7x7", "5x5"), ("7vs7", "5vs5")], max_length=10
            ),
        ),
    ]
