# Generated by Django 4.1.7 on 2023-04-09 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('is_public', models.BooleanField(default='False')),
                ('price', models.FloatField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.field')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='reservations.player')),
                ('players', models.ManyToManyField(related_name='players', to='reservations.player')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.typefield'),
        ),
    ]
