# Generated by Django 4.1.7 on 2023-03-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
