# Generated by Django 4.1.7 on 2023-04-04 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootBallField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FootBallFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('max', models.IntegerField()),
                ('price', models.FloatField()),
                ('advance', models.FloatField()),
                ('footBallField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field_type.footballfield')),
            ],
        ),
    ]
