# Generated by Django 4.1.7 on 2023-04-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field_type', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballfieldtype',
            name='footBallField',
        ),
    ]
