# Generated by Django 4.1.7 on 2023-04-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field_type', '0002_remove_footballfieldtype_footballfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballfieldtype',
            old_name='price',
            new_name='priceHour',
        ),
        migrations.RemoveField(
            model_name='footballfieldtype',
            name='advance',
        ),
    ]
